"""empty message

Revision ID: 01929216e61f
Revises: da413465fd3c
Create Date: 2019-05-04 20:55:33.008609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01929216e61f'
down_revision = 'da413465fd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like')
    # ### end Alembic commands ###
